name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-source:
    runs-on: ubuntu-latest
    env:
      # These are needed in order to publish the final build artifacts into GitHub package registry
      USERNAME: ${{ github.actor }}
      TOKEN: ${{ secrets.TOKEN }}
      DOCKER_CR_OAUTH_TOKEN: ${{ secrets.DOCKER_CR_OAUTH_TOKEN }}
      CR_URL: ${{ vars.CR_URL }}
      CR_REPOSITORY: ${{ vars.CR_REPOSITORY }}
      KUBE_CONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B -s settings.xml clean package

      - name: Set up Docker
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
        uses: docker/setup-docker-action@v4

      - name: Build Docker Image
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
        run: |
          docker build --tag $CR_URL/$CR_REPOSITORY/spring-petclinic:3.5.0-SNAPSHOT --file docker/Dockerfile .

      - name: Docker login to Yandex Cloud CR
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
        run: echo $DOCKER_CR_OAUTH_TOKEN | docker login --username oauth --password-stdin $CR_URL

      - name: Docker push to Yandex Cloud CR
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
        run: docker push $CR_URL/$CR_REPOSITORY/spring-petclinic:3.5.0-SNAPSHOT

      - name: Docker logout
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
        run: docker logout

      - name: Setup Helm
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.14.0

      - name: Deploy spring-petclinic to K8S
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
        working-directory: chart
        run: |
          mkdir -p ~/.kube
          touch ~/.kube/config
          echo "$KUBE_CONFIG_BASE64" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          helm upgrade --install petclinic . --set image.ref=$CR_URL/$CR_REPOSITORY/spring-petclinic:3.5.0-SNAPSHOT -f values.yaml
